In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
pd.set_option('display.max_columns', None)
import warnings
warnings.filterwarnings("ignore")

In [31]:
url = "/Users/chimuanyaazike/Desktop/Churn/Churn/cleaned_data.csv"
data = pd.read_csv(url)
data.head()

,CustomerID,Name,Age,Gender,Location,Email,Phone,Address,Segment,NPS,ChurnLabel,Timestamp,TotalPurchaseFrequency,TotalPurchaseValue,ProductList,Plan,Start_Date,End_Date,TotalInteractionType,numEmails,numCalls,numChats,FirstInteractionDate,LastInteractionDate,AVGLatePayment,NumPaymentMethods,PageViews,TimeSpent(minutes),ActionCount,unique_pages,most_recent_action_date,Logins,Frequency,Rating,Comment,AVGOpenDays,AVGClickDays
0,1001,Mark Barrett,31,Male,Andrewfort,allison74@example.net,3192528777,"61234 Shelley Heights Suite 467\nCohentown, GU...",Segment B,3,1,2020-01-27 01:36:49,38,3994.72,Frozen Cocktail Mixes|Guacamole|Hockey Stick C...,Express,2020-06-08,2022-10-27,Call|Chat|Email,1,1,2,2019-09-26,2021-07-25,13.333333,3,49,15,24,13,2022-11-07 02:24:31,19,Weekly,1,I move baby go small big. Office institution s...,818.0,319.0
1,1002,Jeremy Welch,66,Female,Millerhaven,fmiller@example.com,231-587-1818x8651,"4959 Jennifer Junction\nNew Angelaport, TN 87397",Segment C,6,0,2019-01-06 18:30:03,4,2844.35,Baby Protective Wear|Footbags|Watercraft Polishes,Pro,2021-07-21,2022-05-07,Call|Chat|Email,10,5,4,2019-01-12,2022-12-13,3.333333,3,100,9,24,13,2022-12-05 00:27:08,9,Weekly,2,Wish what bag cut life. Statement might opport...,110.0,88.0
2,1003,Brandon Patel,36,Female,Lozanostad,jasonbrown@example.org,(270)633-9095,"38701 Amanda Brook Apt. 076\nKimshire, NJ 62516",Segment B,3,0,2019-04-30 04:25:10,14,1866.52,"Fudge|Pipe Caps & Plugs|Vehicle Waxes, Polishe...",Essential,2019-10-05,2020-08-19,Call|Chat|Email,1,1,1,2019-10-09,2022-01-04,2.666667,3,1,97,12,7,2022-11-02 15:59:43,19,Monthly,4,Some Democrat guess but short. Whether behind ...,333.0,117.0
3,1004,Tina Martin,62,Female,South Dustin,matthew62@example.net,050.081.8706x11982,"67324 Ashley Coves\nSouth John, RI 29650",Segment C,1,1,2020-03-03 17:33:28,28,1378.64,CrÃªpe & Blini Pans|Electrical Switches|Mouthwa...,Smart,2020-01-14,2022-03-27,Call|Chat|Email,18,17,24,2019-01-03,2022-11-10,26.333333,3,25,31,47,14,2022-12-08 18:10:18,4,Daily,1,Yard feel never miss ask billion Congress. Fly...,159.0,423.0
4,1005,Christopher Rodriguez,68,Female,West James,shannonstrickland@example.org,+1-701-854-4915x724,"01169 Miller Mission\nWest Anthonyburgh, WY 47359",Segment C,3,0,2019-04-05 22:42:22,39,2425.05,Audiobooks|Fire Extinguisher & Equipment Stora...,Basic,2021-04-08,2022-11-09,Call|Chat|Email,5,4,1,2019-04-10,2022-12-19,0.666667,3,77,51,30,12,2022-12-30 23:37:00,12,Weekly,3,Ten determine unit interview challenge stock. ...,193.0,96.0

In [32]:
data.shape

(12483, 37)

In [33]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12483 entries, 0 to 12482
Data columns (total 37 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   CustomerID               12483 non-null  int64
 1   Name                     12483 non-null  object
 2   Age                      12483 non-null  int64
 3   Gender                   12483 non-null  object
 4   Location                 12483 non-null  object
 5   Email                    12483 non-null  object
 6   Phone                    12483 non-null  object
 7   Address                  12483 non-null  object
 8   Segment                  12483 non-null  object
 9   NPS                      12483 non-null  int64
 10  ChurnLabel               12483 non-null  int64
 11  Timestamp                12483 non-null  object
 12  TotalPurchaseFrequency   12483 non-null  int64
 13  TotalPurchaseValue       12483 non-null  float64
 14  ProductList              12483 non-null  object
 15  Plan                     12483 non-null  object
 16  Start_Date               12483 non-null  object
 17  End_Date                 12483 non-null  object
 18  TotalInteractionType     12483 non-null  object
 19  numEmails                12483 non-null  int64
 20  numCalls                 12483 non-null  int64
 21  numChats                 12483 non-null  int64
 22  FirstInteractionDate     12483 non-null  object
 23  LastInteractionDate      12483 non-null  object
 24  AVGLatePayment           12483 non-null  float64
 25  NumPaymentMethods        12483 non-null  int64
 26  PageViews                12483 non-null  int64
 27  TimeSpent(minutes)       12483 non-null  int64
 28  ActionCount              12483 non-null  int64
 29  unique_pages             12483 non-null  int64
 30  most_recent_action_date  12483 non-null  object
 31  Logins                   12483 non-null  int64
 32  Frequency                12483 non-null  object
 33  Rating                   12483 non-null  int64
 34  Comment                  12483 non-null  object
 35  AVGOpenDays              12483 non-null  float64
 36  AVGClickDays             12483 non-null  float64
dtypes: float64(4), int64(15), object(18)
memory usage: 3.5+ MB

In [11]:
data.duplicated().sum()

np.int64(0)

In [14]:
data.isnull().sum()

CustomerID                 0
Name                       0
Age                        0
Gender                     0
Location                   0
Email                      0
Phone                      0
Address                    0
Segment                    0
NPS                        0
ChurnLabel                 0
Timestamp                  0
TotalPurchaseFrequency     0
TotalPurchaseValue         0
ProductList                0
Plan                       0
Start_Date                 0
End_Date                   0
TotalInteractionType       0
numEmails                  0
numCalls                   0
numChats                   0
FirstInteractionDate       0
LastInteractionDate        0
AVGLatePayment             0
NumPaymentMethods          0
PageViews                  0
TimeSpent(minutes)         0
ActionCount                0
unique_pages               0
most_recent_action_date    0
Logins                     0
Frequency                  0
Rating                     0
Comment                    0
AVGOpenDays                0
AVGClickDays               0
dtype: int64

In [ ]:
data['Gender'] # this is called subsettiing

0          Male
1        Female
2        Female
3        Female
4        Female
          ...
12478    Female
12479      Male
12480      Male
12481    Female
12482      Male
Name: Gender, Length: 12483, dtype: object

In [16]:
data.columns

Index(['CustomerID', 'Name', 'Age', 'Gender', 'Location', 'Email', 'Phone',
       'Address', 'Segment', 'NPS', 'ChurnLabel', 'Timestamp',
       'TotalPurchaseFrequency', 'TotalPurchaseValue', 'ProductList', 'Plan',
       'Start_Date', 'End_Date', 'TotalInteractionType', 'numEmails',
       'numCalls', 'numChats', 'FirstInteractionDate', 'LastInteractionDate',
       'AVGLatePayment', 'NumPaymentMethods', 'PageViews',
       'TimeSpent(minutes)', 'ActionCount', 'unique_pages',
       'most_recent_action_date', 'Logins', 'Frequency', 'Rating', 'Comment',
       'AVGOpenDays', 'AVGClickDays'],
      dtype='object')

In [18]:
### pd.to_datetime(data["Start_Date"]error="coerce") #this is a single column conversion to datetime, however when we have multiple columns to convert, we use a loop for efficiency

In [49]:

col_to_date = ['Start_Date', 'End_Date', 'FirstInteractionDate', 'Timestamp', 'LastInteractionDate', 'most_recent_action_date'] #list of columns to convert to datetime, col stands for column

for col in col_to_date:
    data[col] = pd.to_datetime(data[col], errors='coerce')

In [50]:
data.dtypes

CustomerID                          int64
Name                               object
Age                                 int64
Gender                             object
Location                           object
Email                              object
Phone                              object
Address                            object
Segment                            object
NPS                                 int64
ChurnLabel                          int64
Timestamp                  datetime64[ns]
TotalPurchaseFrequency              int64
TotalPurchaseValue                float64
ProductList                        object
Plan                               object
Start_Date                 datetime64[ns]
End_Date                   datetime64[ns]
TotalInteractionType               object
numEmails                           int64
numCalls                            int64
numChats                            int64
FirstInteractionDate       datetime64[ns]
LastInteractionDate        datetime64[ns]
AVGLatePayment                    float64
NumPaymentMethods                   int64
PageViews                           int64
TimeSpent(minutes)                  int64
ActionCount                         int64
unique_pages                        int64
most_recent_action_date    datetime64[ns]
Logins                              int64
Frequency                          object
Rating                              int64
Comment                            object
AVGOpenDays                       float64
AVGClickDays                      float64
churnDate                  datetime64[ns]
churnTime                  datetime64[ns]
dtype: object

In [21]:
data['Timestamp']

0        2020-01-27 01:36:49
1        2019-01-06 18:30:03
2        2019-04-30 04:25:10
3        2020-03-03 17:33:28
4        2019-04-05 22:42:22
                ...
12478    2022-01-27 00:27:28
12479    2020-06-14 23:04:47
12480    2020-10-13 15:09:13
12481    2020-06-24 23:49:01
12482    2022-07-14 07:27:52
Name: Timestamp, Length: 12483, dtype: object

In [35]:
data['churnDate'] = data['Timestamp'].dt.date
data['churnTime'] = data['Timestamp'].dt.time

In [ ]:
# data['churnDate'] = data['Timestamp'].str.split(' ').str[0]# this splits the timestamp into date and time and selects only the date part
# data['churnTime'] = data['Timestamp'].str.split(' ').str[1]

0        2020-01-27
1        2019-01-06
2        2019-04-30
3        2020-03-03
4        2019-04-05
            ...
12478    2022-01-27
12479    2020-06-14
12480    2020-10-13
12481    2020-06-24
12482    2022-07-14
Name: Timestamp, Length: 12483, dtype: object

In [ ]:
# data['churnDate'] = data['Timestamp'].str.split(' ').str[0]# this splits the timestamp into date and time and selects only the date part
# data['churnTime'] = data['Timestamp'].str.split(' ').str[1]

# data.drop(columns=['Timestamp'], inplace=True)

In [40]:
data['churnDate'] = pd.to_datetime(data['churnDate'], errors='coerce')

In [41]:
data['churnTime'] = pd.to_datetime(data['churnTime'], errors='coerce')

In [46]:
data['most_recent_action_date']

0        2022-11-07
1        2022-12-05
2        2022-11-02
3        2022-12-08
4        2022-12-30
            ...
12478    2022-10-02
12479    2022-11-10
12480    2022-11-20
12481    2022-09-08
12482    2022-11-22
Name: most_recent_action_date, Length: 12483, dtype: object

In [ ]:
data['most_recent_action_time'] = data['most_recent_action_date'].dt.time
data['most_recent_action_date'] = data['most_recent_action_date'].dt.date


data['most_recent_action_date'] = pd.to_datetime(data['most_recent_action_date'], errors='coerce')

In [52]:
data.drop(columns =['Timestamp', 'most_recent_action_time', 'churnTime'], inplace=True)

In [53]:
data.dtypes

CustomerID                          int64
Name                               object
Age                                 int64
Gender                             object
Location                           object
Email                              object
Phone                              object
Address                            object
Segment                            object
NPS                                 int64
ChurnLabel                          int64
TotalPurchaseFrequency              int64
TotalPurchaseValue                float64
ProductList                        object
Plan                               object
Start_Date                 datetime64[ns]
End_Date                   datetime64[ns]
TotalInteractionType               object
numEmails                           int64
numCalls                            int64
numChats                            int64
FirstInteractionDate       datetime64[ns]
LastInteractionDate        datetime64[ns]
AVGLatePayment                    float64
NumPaymentMethods                   int64
PageViews                           int64
TimeSpent(minutes)                  int64
ActionCount                         int64
unique_pages                        int64
most_recent_action_date    datetime64[ns]
Logins                              int64
Frequency                          object
Rating                              int64
Comment                            object
AVGOpenDays                       float64
AVGClickDays                      float64
churnDate                  datetime64[ns]
dtype: object

In [54]:
data.to_csv('cleaned_data.csv', index=False)

## Preprocessing for our Model

In [58]:
data_col_to_engineer = data.select_dtypes(include= 'datetime64').columns.tolist()

for col in data_col_to_engineer:
    data[col + '_year'] = data[col].dt.year
    data[col + '_month'] = data[col].dt.month
    data[col + '_day'] = data[col].dt.day

    data.drop(columns=[col], inplace=True)

## Encode catergory variables

In [61]:
data.drop(columns= ['Name','Email','Phone'], inplace=True)

In [68]:
data.select_dtypes(include='object')

,Gender,Location,Address,Segment,ProductList,Plan,TotalInteractionType,Frequency,Comment
0,Male,Andrewfort,"61234 Shelley Heights Suite 467\nCohentown, GU...",Segment B,Frozen Cocktail Mixes|Guacamole|Hockey Stick C...,Express,Call|Chat|Email,Weekly,I move baby go small big. Office institution s...
1,Female,Millerhaven,"4959 Jennifer Junction\nNew Angelaport, TN 87397",Segment C,Baby Protective Wear|Footbags|Watercraft Polishes,Pro,Call|Chat|Email,Weekly,Wish what bag cut life. Statement might opport...
2,Female,Lozanostad,"38701 Amanda Brook Apt. 076\nKimshire, NJ 62516",Segment B,"Fudge|Pipe Caps & Plugs|Vehicle Waxes, Polishe...",Essential,Call|Chat|Email,Monthly,Some Democrat guess but short. Whether behind ...
3,Female,South Dustin,"67324 Ashley Coves\nSouth John, RI 29650",Segment C,CrÃªpe & Blini Pans|Electrical Switches|Mouthwa...,Smart,Call|Chat|Email,Daily,Yard feel never miss ask billion Congress. Fly...
4,Female,West James,"01169 Miller Mission\nWest Anthonyburgh, WY 47359",Segment C,Audiobooks|Fire Extinguisher & Equipment Stora...,Basic,Call|Chat|Email,Weekly,Ten determine unit interview challenge stock. ...
...,...,...,...,...,...,...,...,...,...
12478,Female,New Lauren,"836 Gonzalez Drive Apt. 334\nLake Kelly, RI 01667",Segment A,Concrete & Masonry Cleaners|Ice Cream Noveltie...,Essential,Call|Chat|Email,Daily,Light appear fight lawyer where star.
12479,Male,Randymouth,3715 Wiggins Harbors Suite 139\nEast Gregorybo...,Segment A,Straight Pins,Flex,Call|Chat,Weekly,Yet very girl history. Thing late dream you re...
12480,Male,East Erin,"56050 Steven Summit Suite 383\nJohnmouth, NM 2...",Segment C,Cabbage|Fabric Refreshers|Furisode Kimonos|Gol...,Deluxe,Call|Chat|Email,Monthly,Offer particularly single degree seem sound. S...
12481,Female,New Leah,"72356 Teresa Rapid\nPorterborough, SC 40076",Segment A,Clear Kerosene|Dice Sets & Games|Pot Racks|Seq...,Gold,Call|Chat|Email,Monthly,Rest something concern likely movie. Foot in i...
12482,Male,West Amanda,USCGC Lopez\nFPO AE 85542,Segment C,Pool Brushes & Brooms,Prime,Call|Chat|Email,Weekly,Indeed foot trouble heavy agreement cut. West ...

- one hot Encoder
- label Encoder
- target Encoder
- frequency Encoder
- binary Encoder
- mean Encoder